[profile.default]
src = "contracts"
out = "out"
test = "test"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1
evm_version = "paris"
via_ir = true

[invariant]
runs = 32
depth = 32
fail_on_revert = false
